#!/bin/bash

# Live Demo Test - Transylvania Hotel Booking System
# Run this to test the full booking flow

clear
echo "======================================"
echo "🏰 TRANSYLVANIA HOTEL BOOKING DEMO"
echo "======================================"
echo ""
echo "✅ Backend running on: http://localhost:8080"
echo "✅ Frontend running on: http://localhost:3000"
echo ""
echo "======================================"
echo "📋 DEMO INSTRUCTIONS"
echo "======================================"
echo ""
echo "Step 1: Open your browser"
echo "   → http://localhost:3000"
echo ""
echo "Step 2: Register a New Account"
echo "   Click 'Sign Up' button"
echo "   Name: Your Name"
echo "   Email: demo@hotel.com"
echo "   Password: demo123"
echo "   Click 'Register'"
echo ""
echo "Step 3: Browse Hotels"
echo "   You'll see 5 hotels:"
echo "   🏰 Castle Dracula - \$250/night (⭐4.8)"
echo "   🏨 Grand Hotel Budapest - \$180/night (⭐4.7)"
echo "   ⛰️  Carpathian Resort - \$150/night (⭐4.5)"
echo "   🏛️  Danube Palace - \$220/night (⭐4.9)"
echo "   🏖️  Black Sea Resort - \$130/night (⭐4.3)"
echo ""
echo "Step 4: Select Castle Dracula"
echo "   Click on 'Castle Dracula' card"
echo "   View hotel details and amenities"
echo ""
echo "Step 5: Choose a Room"
echo "   Three room types available:"
echo "   • Standard Room - \$200/night (2 guests)"
echo "   • Deluxe Suite - \$360/night (3 guests)"
echo "   • Royal Suite - \$675/night (4 guests)"
echo ""
echo "   Click 'Book Now' on Deluxe Suite"
echo ""
echo "Step 6: Complete Booking Form"
echo "   Check-in: Click calendar, select Dec 20, 2025"
echo "   Check-out: Click calendar, select Dec 23, 2025"
echo "   Guests: Select 2"
echo "   Special Requests: 'Late check-in around 10 PM, extra pillows'"
echo ""
echo "Step 7: Review & Confirm"
echo "   Review booking summary:"
echo "   - Room: Deluxe Suite"
echo "   - Dates: Dec 20-23, 2025 (3 nights)"
echo "   - Price: \$360 × 3 = \$1,080"
echo "   - Guests: 2"
echo ""
echo "   Click 'Confirm Booking' button"
echo ""
echo "Step 8: View Booking Confirmation"
echo "   You'll see success message"
echo "   Booking ID will be shown"
echo ""
echo "Step 9: Check Your Dashboard"
echo "   Click 'Dashboard' in navigation"
echo "   See your booking listed with:"
echo "   - Booking details"
echo "   - Status: CONFIRMED"
echo "   - Total price"
echo "   - Check-in/Check-out dates"
echo ""
echo "======================================"
echo "🧪 TEST WITH API (Optional)"
echo "======================================"
echo ""
echo "# Register user:"
echo "curl -X POST http://localhost:8080/api/auth/register \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"name\":\"Demo User\",\"email\":\"demo2@hotel.com\",\"password\":\"demo123\",\"role\":\"CUSTOMER\"}'"
echo ""
echo "# Login:"
echo "curl -X POST http://localhost:8080/api/auth/login \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"email\":\"demo2@hotel.com\",\"password\":\"demo123\"}'"
echo ""
echo "# View hotels:"
echo "curl http://localhost:8080/api/hotels"
echo ""
echo "# View rooms:"
echo "curl http://localhost:8080/api/hotels/1/rooms"
echo ""
echo "======================================"
echo "✨ DEMO READY!"
echo "======================================"
echo ""
echo "Press Enter to open the web application..."
read

# Try to open browser
if command -v xdg-open > /dev/null; then
    xdg-open http://localhost:3000
elif command -v open > /dev/null; then
    open http://localhost:3000
else
    echo "Please open http://localhost:3000 in your browser"
fi

echo ""
echo "Enjoy your demo! 🎉"
