// Mock data for demo purposes when backend is unavailable
export const mockHotels = [
  {
    id: 1,
    name: "Grand Horizon Resort",
    location: "Maldives",
    description: "Luxury overwater villas with private pools and stunning ocean views",
    rating: 4.9,
    amenities: ["Pool", "Spa", "Restaurant", "WiFi", "Gym", "Beach Access"],
    imageUrl: "/luxury-maldives-overwater-villa-resort.jpg",
    pricePerNight: 450,
  },
  {
    id: 2,
    name: "Alpine Mountain Lodge",
    location: "Swiss Alps",
    description: "Cozy mountain retreat with panoramic alpine views and world-class skiing",
    rating: 4.8,
    amenities: ["Ski Access", "Restaurant", "WiFi", "Spa", "Fireplace"],
    imageUrl: "/luxury-swiss-alps-mountain-lodge-winter.jpg",
    pricePerNight: 320,
  },
  {
    id: 3,
    name: "Sunset Beach Villa",
    location: "Bali, Indonesia",
    description: "Private beachfront villa with infinity pool and traditional Balinese architecture",
    rating: 4.9,
    amenities: ["Beach Access", "Pool", "Spa", "Restaurant", "WiFi", "Butler Service"],
    imageUrl: "/luxury-bali-beach-villa-sunset-pool.jpg",
    pricePerNight: 380,
  },
  {
    id: 4,
    name: "Metropolitan Plaza Hotel",
    location: "New York City",
    description: "Sophisticated urban hotel in the heart of Manhattan with skyline views",
    rating: 4.7,
    amenities: ["Gym", "Restaurant", "Bar", "WiFi", "Business Center", "Rooftop Terrace"],
    imageUrl: "/luxury-new-york-city-hotel-skyline.jpg",
    pricePerNight: 420,
  },
  {
    id: 5,
    name: "Desert Oasis Resort",
    location: "Dubai, UAE",
    description: "Opulent desert resort with gold-accented suites and world-class dining",
    rating: 4.9,
    amenities: ["Pool", "Spa", "Restaurant", "WiFi", "Golf Course", "Private Beach"],
    imageUrl: "/luxury-dubai-desert-resort-oasis.jpg",
    pricePerNight: 520,
  },
  {
    id: 6,
    name: "Tuscan Countryside Estate",
    location: "Tuscany, Italy",
    description: "Historic villa surrounded by vineyards with authentic Italian charm",
    rating: 4.8,
    amenities: ["Pool", "Restaurant", "WiFi", "Wine Tasting", "Cooking Classes"],
    imageUrl: "/luxury-tuscany-villa-vineyard-countryside.jpg",
    pricePerNight: 290,
  },
]

export const mockRooms = [
  {
    id: 1,
    hotelId: 1,
    type: "Deluxe Suite",
    description: "Spacious suite with king bed and ocean view balcony",
    pricePerNight: 350,
    capacity: 2,
    amenities: ["King Bed", "Balcony", "Mini Bar", "Smart TV"],
    imageUrl: "/luxury-hotel-deluxe-suite-ocean-view.jpg",
    available: true,
  },
  {
    id: 2,
    hotelId: 1,
    type: "Presidential Suite",
    description: "Ultimate luxury with private pool and butler service",
    pricePerNight: 850,
    capacity: 4,
    amenities: ["King Bed", "Private Pool", "Butler", "Living Room", "Kitchen"],
    imageUrl: "/luxury-presidential-suite-private-pool.jpg",
    available: true,
  },
]

export const mockBookings = [
  {
    id: 1,
    hotelName: "Grand Horizon Resort",
    location: "Maldives",
    roomType: "Deluxe Suite",
    checkIn: "2025-02-15",
    checkOut: "2025-02-20",
    guests: 2,
    totalPrice: 1750,
    status: "confirmed",
    imageUrl: "/luxury-maldives-resort.jpg",
  },
  {
    id: 2,
    hotelName: "Alpine Mountain Lodge",
    location: "Swiss Alps",
    roomType: "Mountain View Room",
    checkIn: "2025-01-10",
    checkOut: "2025-01-15",
    guests: 2,
    totalPrice: 1600,
    status: "completed",
    imageUrl: "/swiss-alps-lodge.jpg",
  },
]
